services:
  mysql:
    image: mysql:5.7.37
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: SSDLC
      MYSQL_USER: ServiceUser
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  legacy-php:
    depends_on:
      - mysql
    image: php:5.3.29-apache
    volumes:
      - ./web:/var/www/html
