services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ssdlc
      MYSQL_USER: serviceuser
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      bridge_net:
        ipv4_address: 172.25.0.2

  legacy-php:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    container_name: legacy-php
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    networks:
      bridge_net:
        ipv4_address: 172.25.0.3

  kali-linux:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali
    networks:
      bridge_net:
        ipv4_address: 172.25.0.4
    tty: true
    stdin_open: true

  browsh:
    image: browsh/browsh
    container_name: browsh
    networks:
      bridge_net:
        ipv4_address: 172.25.0.5
    tty: true
    stdin_open: true
    entrypoint: /bin/bash

networks:
  bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/26
